spring:
  application:
    name: microservice-eureka-server
  jmx:
    default-domain: xyz-eureka-server
server:
  port: 8073
  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
